version: "3.8"
services:
      mongodb:

        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:

        - /home/wael/PycharmProjects/fb_scraper/mongodb/database:/data/db
        ports:
        - 27017:27017
        restart: unless-stopped
      fb_scraper:
        image: fb_scraper

        ports:
          - 8000:8000
        depends_on:
         - mongodb
